# Generated by Django 5.1.5 on 2025-01-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_exchanger', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('req', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('amount', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('withdrawed', models.BooleanField(default=False)),
                ('with_course', models.FloatField(blank=True, null=True)),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.telegramuser')),
            ],
        ),
    ]
